apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    service: reverseproxy
